### PR TITLE
Improvements for building the package (Version 2)

### PR DESCRIPTION
**Pull request by c-mauderer**
These are the fixed patches for my original request. Sorry for spamming: Fixing the patches went better and faster than I thought. Now it works.

### CODE REVIEW

**Comment by fawkesley** [comment]
Thanks @c-mauderer !

Sorry for taking ages. Thanks for contributing back, and good work building packages! In response to your message on the other PR:

> By the way: There are at least two other repositories with this driver:
danieloneill/SeikoSLPLinuxDriver and hholzgra/sii_440_cups. The first one seems to have a slightly modified version of the original driver. The later one seems to be a version with less printers supported. It would be nice, if they could be somehow connected on github so that someone who finds one of the repos can also look for improvements in others. Do you have an idea how that might work?

Hmm. It was never really my intention to maintain this repo - I just wanted to dump it somewhere better than the dreadful website I had to download it from.

With the repo laid out as it currently is, I can't explain that in a README so how about I move the repo into a `src/` subdirectory and add a top level README explaining my intention and pointing to the other repos on github?

I think that makes sense - it'll break your build script though, heads up...

Paul

**Comment by c-mauderer** [comment]
Hello @paulfurley 

to be honest: I wasn't even sure whether you would respond at all when I created the ticket. The repository looked exactly how you described it: Some place to archive the code so that it doesn't vanish if SII somewhen decides to drop the support. I just thought that it would be a better approach to try to fork it instead of creating a new copy. So thanks for the response ;-)

For the structure: Moving the sources into a subdirectory might would be a good idea. That would simplify adding some other notes or build scripts too. It's no problem if that breaks the build script. If necessary I'll just adapt it and create a new pull request.

By the way: My Arch-Linux-Package (https://aur.archlinux.org/packages/sii-slp-cups-git/) currently pulls from my fork of the repo. If you are OK with it, I'll move that to your repo too as soon as I can build from it.

**Comment by fawkesley** [comment]
Perfect! I've added the subdirectory and README, and I took the liberty of rebasing your changes and made a new PR #4 - hope that's OK.

Yes I'm OK with your build script building from this repo, no problem.

If you fancy another project, you could make your script my PGP signature ;)

**Comment by c-mauderer** [comment]
Thanks for the rebase. Of course I'm OK with it. I'll adapt the Arch package this weekend.

Just a small correction: You put the Arch package under "Binary Packages". Thats not totally correct. The Arch user repository only hosts the necessary scripts to build the package. To get a package you have to download them and call a "makepkg". So it's more a "Package Distribution" or "Linux Packages".

I'm not totally sure what you mean by the last sentence. Should I check a GPG signature of the repository while building the package?

**Comment by fawkesley** [comment]
Ah, yeah good spot on binary packages, will fix.

Sorry I missed a few words from that last sentence!

I PGP-sign commits on library type repos `git commit --gpg-sign` which verifies that I actually made them, rather than someone who broke into my account, for example. So in theory your build script could check that the latest commit has a valid signature against my public key.

In practice this is (unfortunately) not widely practised, so I don't know how good the tools are for doing that.

The reason for this suggestion (mission!) is that I'm worried by the number of projects that pull in random  github repos / node packages / python / whatever packages with no authentication. It gives an attacker a lot of ways of getting malicious code onto other people's machines.  Perhaps I should write a blog post about this ;)

**Comment by c-mauderer** [comment]
OK. Now I know what you mean. I'll try to add the signature check to the package. Even if I'm quite sure that there would be a lot of simpler possibilities to attack a package in the AUR (Arch User Repository) than to compromise a github repository, it is definitely a step into the right direction to check the sources.

**Pull request closed without merging**
